service: aws-node

frameworkVersion: "2 || 3"

plugins:
  - serverless-bundle
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1

functions:
  getRoot:
    handler: src/server.handler
    memorySize: 128
    events:
      - httpApi:
          path: /
          method: get
